version: '2'
services:

  # The Application
  app:
    container_name: test_app
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    container_name: test_web
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.6
    container_name: test_db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=test_db"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=none"
      - "MYSQL_ROOT_PASSWORD=none"
    ports:
        - 33061:3306
  # The phpmyadmin
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: test_phpmyadmin
    ports:
      - 8088:80
    restart: always
    external_links:
      - database:mysql
    depends_on:
      - database
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: none
      MYSQL_ROOT_PASSWORD: none
      PMA_HOST: database

volumes:
  dbdata:
